import type { Metadata } from "next";
import{ Toaster } from "sonner"
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
export const metadata: Metadata = {
  title: "Ticket Solver",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>
        {children}
        <Toaster position="top-right" richColors />
        </AuthProvider>
      </body>
    </html>
  )
}

