import type { Metadata } from "next";
import { Toaster } from "sonner"
import "./globals.css";
import Provider from "@/app/provider";
export const metadata: Metadata = {
  title: "Ticket Solver",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Provider>
          {children}
        </Provider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}

